DIR = /usr/bin
.PHONY: all doc clean

all: warcraft editeur

#Compilations
%.o: %.c %.h
	$(CC) $(CFLAGS) -c $< -o $@

#Editions de lien
%: %.o
	$(CC) $^ -o $@

#Dependences editions de liens
warcraft: warcraft.o video.o perso.o
editeur: editeur.o perso.o video.o

#Dependances
depends:
	makedepend -Y *.c

#Clean
clean:
	rm -f *.o warcraft editeur

#Installation
install:
	install -D . $(PREFIX)$(DIR)
	install -m 644 $(PREFIX)$(DIR)

# DO NOT DELETE

editeur.o: perso.h video.h editeur.h
perso.o: perso.h video.h
video.o: video.h
warcraft.o: video.h perso.h warcraft.h
